---
name: Application Publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        arch: [ 'x64', 'arm64' ]
        exclude:
          # Mitigation for Electron Forge naming conflict. See #1183.
          - os: 'windows-latest'
            arch: 'arm64'
          # GitHub Actions has no native arm64 Ubuntu runners
          - os: 'ubuntu-latest'
            arch: 'arm64'
        
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Setup Node (v20)
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn --immutable

      - name: Build (${{ matrix.arch }})
        env:
          YTD_UPDATE_FEED_OWNER: ${{ vars.YTD_UPDATE_FEED_OWNER }}
          YTD_UPDATE_FEED_REPOSITORY: ${{ vars.YTD_UPDATE_FEED_REPOSITORY }}
        run: yarn make --arch ${{ matrix.arch }}

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            out/make/**/*.exe
            out/make/**/*.nupkg
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.zip
            out/make/**/*.dmg
            out/make/**/*.AppImage
